//
//  SearchModels.swift
//  Reciplease
//
//  Created by Thibault Bargat on 21/03/2019.
//  Copyright (c) 2019 Thibault Bargat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum Fetch
  {
    struct Request
    {
    }
    struct Response
    {
        var recipesArrayObj: [Recipe]?
        var ingredients: [String]?
        var isError: Bool
        var message: String?
    }
    struct ViewModel
    {
        var displayedIngredients: String
    }
  }
}
